branches:
  only:
    - develop
    - master
    - livedoc

script:
  - cd bin # Temp workaround to prevent the default rake script from running.

deploy:
  provider: s3
  access_key_id:
    secure: "L3TXxQJZutXrXROf89dTiMuvcnsQ88F+cSqpddhafy4O3agyTMyJcHozizCaKI+VuJVZnUrip/joo4b85PSC8xjU4G7/lOIAoiSyQZU/f4RqUTFyl9ppTHQq2CyZKZy1qhqmBegRcWTy6TLV3JNXzKq+0fgl6/HekUMBuNX98yM="
  secret_access_key:
    secure: "L3TXxQJZutXrXROf89dTiMuvcnsQ88F+cSqpddhafy4O3agyTMyJcHozizCaKI+VuJVZnUrip/joo4b85PSC8xjU4G7/lOIAoiSyQZU/f4RqUTFyl9ppTHQq2CyZKZy1qhqmBegRcWTy6TLV3JNXzKq+0fgl6/HekUMBuNX98yM="
  bucket: install.prediction.io
  region: us-east-1
  skip_cleanup: true
  endpoint: install.prediction.io.s3-website-us-east-1.amazonaws.com
  local-dir: bin
  detect_encoding: true
  on: develop